---
# 検証・証跡取得
evidence_dir_remote: 'C:\build_evidence'
evidence_dir_local: "{{ playbook_dir }}/../evidence"
verify_fail_on_mismatch: false     # true にすると設計値と不一致でタスクを失敗させる

# 突合せの期待値を切り替えるための参照（実体は group_vars/all/main.yml で定義する）
enable_domain_join: false
ad_domain_name: "PICKLES-CORP.pickles.co.jp"
